### PR TITLE
ACS_Table_Final

### PR DESCRIPTION
**Pull request by ShihengXu**
[ACS_table_with_labels.csv.zip](https://github.com/user-attachments/files/17536041/ACS_table_with_labels.csv.zip)

### CODE REVIEW

**Comment by dhruvds58** [comment]
Hey Shiheng, can you explain which columns you picked and why? Just trying to understand your thinking.

**Comment by ShihengXu** [comment]
> Hey Shiheng, can you explain which columns you picked and why? Just trying to understand your thinking.

Total population (Available in ACS Table B01003_001E)
Median Gross rent for 2 bedroom apartment (Available in ACS Table B25031_004E)
Median household income in past 12 months (Available in ACS Table B19013_001E)
Poverty rate (Available in ACS Table B17001_001E)
Rental vacancy rate (Available in ACS Table b25004_001E)
Percent renter households (Available in ACS Table B25008_001E)
Percent cost-burdened renters, i.e. households paying >30% income toward rent, (Available in ACS Table B25106_006E, _010E, _014E, _018E)
Unemployment rate (Available in ACS Table B23001_00E)

**Comment by ShihengXu** [comment]
> > Hey Shiheng, can you explain which columns you picked and why? Just trying to understand your thinking.
> 
> Total population (Available in ACS Table B01003_001E) Median Gross rent for 2 bedroom apartment (Available in ACS Table B25031_004E) Median household income in past 12 months (Available in ACS Table B19013_001E) Poverty rate (Available in ACS Table B17001_001E) Rental vacancy rate (Available in ACS Table b25004_001E) Percent renter households (Available in ACS Table B25008_001E) Percent cost-burdened renters, i.e. households paying >30% income toward rent, (Available in ACS Table B25106_006E, _010E, _014E, _018E) Unemployment rate (Available in ACS Table B23001_00E)

Also I think I do not have permission to add a reviewer when I trying to make a new pull request.

**Comment by dhruvds58** [comment]
I don't see these columns in the table, here are the ones I am seeing Estimate!!Total:	Estimate!!Total:!!Owner-occupied housing units:!!Less than $20,000:!!30 percent or more	Estimate!!Total:!!Owner-occupied housing units:!!$20,000 to $34,999:!!30 percent or more	Estimate!!Total:!!Owner-occupied housing units:!!$35,000 to $49,999:!!30 percent or more	Estimate!!Total:!!Owner-occupied housing units:!!$50,000 to $74,999:!!30 percent or more	Estimate!!Total:	Estimate!!Total:	Estimate!!Median gross rent --!!Total:!!2 bedrooms	Estimate!!Total:	Estimate!!Median household income in the past 12 months (in 2022 inflation-adjusted dollars)	Estimate!!Total


are you sure you are pushing the correct file?

**Comment by ShihengXu** [comment]
> I don't see these columns in the table, here are the ones I am seeing Estimate!!Total: Estimate!!Total:!!Owner-occupied housing units:!!Less than $20,000:!!30 percent or more Estimate!!Total:!!Owner-occupied housing units:!!$20,000 to $34,999:!!30 percent or more Estimate!!Total:!!Owner-occupied housing units:!!$35,000 to $49,999:!!30 percent or more Estimate!!Total:!!Owner-occupied housing units:!!$50,000 to $74,999:!!30 percent or more Estimate!!Total: Estimate!!Total: Estimate!!Median gross rent --!!Total:!!2 bedrooms Estimate!!Total: Estimate!!Median household income in the past 12 months (in 2022 inflation-adjusted dollars) Estimate!!Total
> 
> are you sure you are pushing the correct file?

Yes, I have just download it and see it is correct. Have you open it on laptop? Is ACS_table_with_labels.csv.zip what you open?

**Comment by dhruvds58** [comment]
Yeah I opened it on laptop, can you send me a screenshot of the data on slack, make sure all column names are fully visible!

**Comment by ShihengXu** [comment]
> Yeah I opened it on laptop, can you send me a screenshot of the data on slack, make sure all column names are fully visible!

I have uploaded dataset on slack.

**Review by dhruvds58 — APPROVED** [review]

**Pull request merged**
